### ISSUE TITLE
`make run` Can't find `lovefile`

### ISSUE THREAD

**Issue by scillidan** [CSaratakij/LovePlayground#1]
Nihao, I encountered an error in the `make run` step.
The `lovegame` bin can run from the file manager.

![image](https://user-images.githubusercontent.com/19889610/225041591-6a515eaa-b37a-49e7-b764-abbfbe5ad2f3.png)

I tried to enter the commands in Makefile. It said no `lovefile` file was found.
I don't know if it's about my phone. I'm using a Galaxy S20, and andriod version is 13.

![image](https://user-images.githubusercontent.com/19889610/225043763-919a657a-70d6-492c-8f5d-6e50ce2580c4.png)

Thanks for read.

**Comment by CSaratakij** [comment]
@scillidan Is command **'make run'** start love2d app at all?

Shell variable substitute is a bit different from Makefile. 
You don't need those parenthesis, '$lovefile' instead of '$(lovefile)'

example
```sh
lovefile=LovePlayground.love
am start -d "file:///sdcard/Download/lovegame/$lovefile" --user 0 -t "application/*" -n org.love2d.android/.GameActivity
```

If love2d start, but cannot find 'LovePlayground.love' (display 'No game' inside )
It's might be Android 10 scoped storage restriction.

The change start in love2d v.11.4, read more [here](https://github.com/love2d/love-android/issues/194)
Try using previous love2d version, I use [love2d v.11.3a](https://github.com/love2d/love-android/releases/tag/11.3a) with android 11

Don't forget to allow file permission in love2d app

**Comment by scillidan** [comment]
@CSaratakij Thanks for your detailed reply :-)
After I install the [love-11.3-android](https://github.com/love2d/love/releases), 'make run' can start love2d app now.

![image](https://user-images.githubusercontent.com/19889610/225294247-c9a470c2-e2b7-4ed2-acfa-5a49e98d2110.png)
